// GENERADO por ffigen (plantilla: ffigen.template.yaml, script:
// tool/gen_bindings.sh). No editar a mano.
// ODE 0.16.6, dSINGLE. Superficie: la que usa OdeSimulation.
// ignore_for_file: type=lint, unused_field, unused_element

// AUTO GENERATED FILE, DO NOT EDIT.
//
// Generated by `package:ffigen`.
// ignore_for_file: unused_import
import 'dart:ffi' as ffi;

/// ODE 0.16.6, single precision, subconjunto para el backend OdeSimulation (mundo, cuerpos, geoms primitivos, joints hinge/fixed/contact).
class OdeBindings {
  /// Holds the symbol lookup function.
  final ffi.Pointer<T> Function<T extends ffi.NativeType>(String symbolName)
  _lookup;

  /// The symbols are looked up in [dynamicLibrary].
  OdeBindings(ffi.DynamicLibrary dynamicLibrary)
    : _lookup = dynamicLibrary.lookup;

  /// The symbols are looked up with [lookup].
  OdeBindings.fromLookup(
    ffi.Pointer<T> Function<T extends ffi.NativeType>(String symbolName) lookup,
  ) : _lookup = lookup;

  late final ffi.Pointer<ffi.Pointer<_IO_FILE>> _stdin =
      _lookup<ffi.Pointer<_IO_FILE>>('stdin');

  ffi.Pointer<_IO_FILE> get stdin => _stdin.value;

  set stdin(ffi.Pointer<_IO_FILE> value) => _stdin.value = value;

  late final ffi.Pointer<ffi.Pointer<_IO_FILE>> _stdout =
      _lookup<ffi.Pointer<_IO_FILE>>('stdout');

  ffi.Pointer<_IO_FILE> get stdout => _stdout.value;

  set stdout(ffi.Pointer<_IO_FILE> value) => _stdout.value = value;

  late final ffi.Pointer<ffi.Pointer<_IO_FILE>> _stderr =
      _lookup<ffi.Pointer<_IO_FILE>>('stderr');

  ffi.Pointer<_IO_FILE> get stderr => _stderr.value;

  set stderr(ffi.Pointer<_IO_FILE> value) => _stderr.value = value;

  late final ffi.Pointer<ffi.Int> _signgam = _lookup<ffi.Int>('signgam');

  int get signgam => _signgam.value;

  set signgam(int value) => _signgam.value = value;

  /// dGetConfiguration returns the specific ODE build configuration as a string
  /// of tokens. The string can be parsed in a similar way to the OpenGL
  /// extension mechanism, the naming convention should be familiar too. The
  /// following extensions are reported:
  ffi.Pointer<ffi.Char> dGetConfiguration() {
    return _dGetConfiguration();
  }

  late final _dGetConfigurationPtr =
      _lookup<ffi.NativeFunction<ffi.Pointer<ffi.Char> Function()>>(
        'dGetConfiguration',
      );
  late final _dGetConfiguration = _dGetConfigurationPtr
      .asFunction<ffi.Pointer<ffi.Char> Function()>();

  /// Helper to check for a token in the ODE configuration string. Caution, this
  /// function is case sensitive.
  int dCheckConfiguration(ffi.Pointer<ffi.Char> token) {
    return _dCheckConfiguration(token);
  }

  late final _dCheckConfigurationPtr =
      _lookup<ffi.NativeFunction<ffi.Int Function(ffi.Pointer<ffi.Char>)>>(
        'dCheckConfiguration',
      );
  late final _dCheckConfiguration = _dCheckConfigurationPtr
      .asFunction<int Function(ffi.Pointer<ffi.Char>)>();

  /// Initializes ODE library.
  int dInitODE2(int uiInitFlags) {
    return _dInitODE2(uiInitFlags);
  }

  late final _dInitODE2Ptr =
      _lookup<ffi.NativeFunction<ffi.Int Function(ffi.UnsignedInt)>>(
        'dInitODE2',
      );
  late final _dInitODE2 = _dInitODE2Ptr.asFunction<int Function(int)>();

  /// Close ODE after it is not needed anymore.
  void dCloseODE() {
    return _dCloseODE();
  }

  late final _dCloseODEPtr = _lookup<ffi.NativeFunction<ffi.Void Function()>>(
    'dCloseODE',
  );
  late final _dCloseODE = _dCloseODEPtr.asFunction<void Function()>();

  late final ffi.Pointer<ffi.Pointer<ffi.Char>> ___tzname =
      _lookup<ffi.Pointer<ffi.Char>>('__tzname');

  ffi.Pointer<ffi.Pointer<ffi.Char>> get __tzname => ___tzname;

  late final ffi.Pointer<ffi.Int> ___daylight = _lookup<ffi.Int>('__daylight');

  int get __daylight => ___daylight.value;

  set __daylight(int value) => ___daylight.value = value;

  late final ffi.Pointer<ffi.Long> ___timezone = _lookup<ffi.Long>(
    '__timezone',
  );

  int get __timezone => ___timezone.value;

  set __timezone(int value) => ___timezone.value = value;

  late final ffi.Pointer<ffi.Pointer<ffi.Char>> _tzname =
      _lookup<ffi.Pointer<ffi.Char>>('tzname');

  ffi.Pointer<ffi.Pointer<ffi.Char>> get tzname => _tzname;

  late final ffi.Pointer<ffi.Int> _daylight = _lookup<ffi.Int>('daylight');

  int get daylight => _daylight.value;

  set daylight(int value) => _daylight.value = value;

  late final ffi.Pointer<ffi.Long> _timezone = _lookup<ffi.Long>('timezone');

  int get timezone => _timezone.value;

  set timezone(int value) => _timezone.value = value;

  void dMassSetZero(ffi.Pointer<dMass> arg0) {
    return _dMassSetZero(arg0);
  }

  late final _dMassSetZeroPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Pointer<dMass>)>>(
        'dMassSetZero',
      );
  late final _dMassSetZero = _dMassSetZeroPtr
      .asFunction<void Function(ffi.Pointer<dMass>)>();

  void dMassSetSphereTotal(
    ffi.Pointer<dMass> arg0,
    double total_mass,
    double radius,
  ) {
    return _dMassSetSphereTotal(arg0, total_mass, radius);
  }

  late final _dMassSetSphereTotalPtr =
      _lookup<
        ffi.NativeFunction<ffi.Void Function(ffi.Pointer<dMass>, dReal, dReal)>
      >('dMassSetSphereTotal');
  late final _dMassSetSphereTotal = _dMassSetSphereTotalPtr
      .asFunction<void Function(ffi.Pointer<dMass>, double, double)>();

  void dMassSetCylinderTotal(
    ffi.Pointer<dMass> arg0,
    double total_mass,
    int direction,
    double radius,
    double length,
  ) {
    return _dMassSetCylinderTotal(arg0, total_mass, direction, radius, length);
  }

  late final _dMassSetCylinderTotalPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Void Function(ffi.Pointer<dMass>, dReal, ffi.Int, dReal, dReal)
        >
      >('dMassSetCylinderTotal');
  late final _dMassSetCylinderTotal = _dMassSetCylinderTotalPtr
      .asFunction<
        void Function(ffi.Pointer<dMass>, double, int, double, double)
      >();

  void dMassSetBoxTotal(
    ffi.Pointer<dMass> arg0,
    double total_mass,
    double lx,
    double ly,
    double lz,
  ) {
    return _dMassSetBoxTotal(arg0, total_mass, lx, ly, lz);
  }

  late final _dMassSetBoxTotalPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Void Function(ffi.Pointer<dMass>, dReal, dReal, dReal, dReal)
        >
      >('dMassSetBoxTotal');
  late final _dMassSetBoxTotal = _dMassSetBoxTotalPtr
      .asFunction<
        void Function(ffi.Pointer<dMass>, double, double, double, double)
      >();

  void dMassAdjust(ffi.Pointer<dMass> arg0, double newmass) {
    return _dMassAdjust(arg0, newmass);
  }

  late final _dMassAdjustPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Pointer<dMass>, dReal)>>(
        'dMassAdjust',
      );
  late final _dMassAdjust = _dMassAdjustPtr
      .asFunction<void Function(ffi.Pointer<dMass>, double)>();

  void dMassRotate(ffi.Pointer<dMass> arg0, ffi.Pointer<dReal> R) {
    return _dMassRotate(arg0, R);
  }

  late final _dMassRotatePtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Void Function(ffi.Pointer<dMass>, ffi.Pointer<dReal>)
        >
      >('dMassRotate');
  late final _dMassRotate = _dMassRotatePtr
      .asFunction<void Function(ffi.Pointer<dMass>, ffi.Pointer<dReal>)>();

  /// Create a new, empty world and return its ID number.
  ffi.Pointer<dxWorld> dWorldCreate() {
    return _dWorldCreate();
  }

  late final _dWorldCreatePtr =
      _lookup<ffi.NativeFunction<ffi.Pointer<dxWorld> Function()>>(
        'dWorldCreate',
      );
  late final _dWorldCreate = _dWorldCreatePtr
      .asFunction<ffi.Pointer<dxWorld> Function()>();

  /// Destroy a world and everything in it.
  void dWorldDestroy(ffi.Pointer<dxWorld> world) {
    return _dWorldDestroy(world);
  }

  late final _dWorldDestroyPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Pointer<dxWorld>)>>(
        'dWorldDestroy',
      );
  late final _dWorldDestroy = _dWorldDestroyPtr
      .asFunction<void Function(ffi.Pointer<dxWorld>)>();

  /// Set the world's global gravity vector.
  void dWorldSetGravity(
    ffi.Pointer<dxWorld> arg0,
    double x,
    double y,
    double z,
  ) {
    return _dWorldSetGravity(arg0, x, y, z);
  }

  late final _dWorldSetGravityPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Void Function(ffi.Pointer<dxWorld>, dReal, dReal, dReal)
        >
      >('dWorldSetGravity');
  late final _dWorldSetGravity = _dWorldSetGravityPtr
      .asFunction<
        void Function(ffi.Pointer<dxWorld>, double, double, double)
      >();

  /// Set the global ERP value, that controls how much error correction is
  /// performed in each time step.
  void dWorldSetERP(ffi.Pointer<dxWorld> arg0, double erp) {
    return _dWorldSetERP(arg0, erp);
  }

  late final _dWorldSetERPPtr =
      _lookup<
        ffi.NativeFunction<ffi.Void Function(ffi.Pointer<dxWorld>, dReal)>
      >('dWorldSetERP');
  late final _dWorldSetERP = _dWorldSetERPPtr
      .asFunction<void Function(ffi.Pointer<dxWorld>, double)>();

  /// Set the global CFM (constraint force mixing) value.
  void dWorldSetCFM(ffi.Pointer<dxWorld> arg0, double cfm) {
    return _dWorldSetCFM(arg0, cfm);
  }

  late final _dWorldSetCFMPtr =
      _lookup<
        ffi.NativeFunction<ffi.Void Function(ffi.Pointer<dxWorld>, dReal)>
      >('dWorldSetCFM');
  late final _dWorldSetCFM = _dWorldSetCFMPtr
      .asFunction<void Function(ffi.Pointer<dxWorld>, double)>();

  /// Quick-step the world.
  int dWorldQuickStep(ffi.Pointer<dxWorld> w, double stepsize) {
    return _dWorldQuickStep(w, stepsize);
  }

  late final _dWorldQuickStepPtr =
      _lookup<
        ffi.NativeFunction<ffi.Int Function(ffi.Pointer<dxWorld>, dReal)>
      >('dWorldQuickStep');
  late final _dWorldQuickStep = _dWorldQuickStepPtr
      .asFunction<int Function(ffi.Pointer<dxWorld>, double)>();

  /// Set the number of iterations that the QuickStep method performs per step.
  void dWorldSetQuickStepNumIterations(ffi.Pointer<dxWorld> arg0, int num) {
    return _dWorldSetQuickStepNumIterations(arg0, num);
  }

  late final _dWorldSetQuickStepNumIterationsPtr =
      _lookup<
        ffi.NativeFunction<ffi.Void Function(ffi.Pointer<dxWorld>, ffi.Int)>
      >('dWorldSetQuickStepNumIterations');
  late final _dWorldSetQuickStepNumIterations =
      _dWorldSetQuickStepNumIterationsPtr
          .asFunction<void Function(ffi.Pointer<dxWorld>, int)>();

  /// Set the maximum correcting velocity that contacts are allowed to generate.
  void dWorldSetContactMaxCorrectingVel(ffi.Pointer<dxWorld> arg0, double vel) {
    return _dWorldSetContactMaxCorrectingVel(arg0, vel);
  }

  late final _dWorldSetContactMaxCorrectingVelPtr =
      _lookup<
        ffi.NativeFunction<ffi.Void Function(ffi.Pointer<dxWorld>, dReal)>
      >('dWorldSetContactMaxCorrectingVel');
  late final _dWorldSetContactMaxCorrectingVel =
      _dWorldSetContactMaxCorrectingVelPtr
          .asFunction<void Function(ffi.Pointer<dxWorld>, double)>();

  /// Set the depth of the surface layer around all geometry objects.
  void dWorldSetContactSurfaceLayer(ffi.Pointer<dxWorld> arg0, double depth) {
    return _dWorldSetContactSurfaceLayer(arg0, depth);
  }

  late final _dWorldSetContactSurfaceLayerPtr =
      _lookup<
        ffi.NativeFunction<ffi.Void Function(ffi.Pointer<dxWorld>, dReal)>
      >('dWorldSetContactSurfaceLayer');
  late final _dWorldSetContactSurfaceLayer = _dWorldSetContactSurfaceLayerPtr
      .asFunction<void Function(ffi.Pointer<dxWorld>, double)>();

  /// Set auto disable linear average threshold for newly created bodies.
  void dWorldSetAutoDisableLinearThreshold(
    ffi.Pointer<dxWorld> arg0,
    double linear_average_threshold,
  ) {
    return _dWorldSetAutoDisableLinearThreshold(arg0, linear_average_threshold);
  }

  late final _dWorldSetAutoDisableLinearThresholdPtr =
      _lookup<
        ffi.NativeFunction<ffi.Void Function(ffi.Pointer<dxWorld>, dReal)>
      >('dWorldSetAutoDisableLinearThreshold');
  late final _dWorldSetAutoDisableLinearThreshold =
      _dWorldSetAutoDisableLinearThresholdPtr
          .asFunction<void Function(ffi.Pointer<dxWorld>, double)>();

  /// Set auto disable angular average threshold for newly created bodies.
  void dWorldSetAutoDisableAngularThreshold(
    ffi.Pointer<dxWorld> arg0,
    double angular_average_threshold,
  ) {
    return _dWorldSetAutoDisableAngularThreshold(
      arg0,
      angular_average_threshold,
    );
  }

  late final _dWorldSetAutoDisableAngularThresholdPtr =
      _lookup<
        ffi.NativeFunction<ffi.Void Function(ffi.Pointer<dxWorld>, dReal)>
      >('dWorldSetAutoDisableAngularThreshold');
  late final _dWorldSetAutoDisableAngularThreshold =
      _dWorldSetAutoDisableAngularThresholdPtr
          .asFunction<void Function(ffi.Pointer<dxWorld>, double)>();

  /// Set auto disable flag for newly created bodies.
  void dWorldSetAutoDisableFlag(
    ffi.Pointer<dxWorld> arg0,
    int do_auto_disable,
  ) {
    return _dWorldSetAutoDisableFlag(arg0, do_auto_disable);
  }

  late final _dWorldSetAutoDisableFlagPtr =
      _lookup<
        ffi.NativeFunction<ffi.Void Function(ffi.Pointer<dxWorld>, ffi.Int)>
      >('dWorldSetAutoDisableFlag');
  late final _dWorldSetAutoDisableFlag = _dWorldSetAutoDisableFlagPtr
      .asFunction<void Function(ffi.Pointer<dxWorld>, int)>();

  /// Create a body in given world.
  ffi.Pointer<dxBody> dBodyCreate(ffi.Pointer<dxWorld> arg0) {
    return _dBodyCreate(arg0);
  }

  late final _dBodyCreatePtr =
      _lookup<
        ffi.NativeFunction<ffi.Pointer<dxBody> Function(ffi.Pointer<dxWorld>)>
      >('dBodyCreate');
  late final _dBodyCreate = _dBodyCreatePtr
      .asFunction<ffi.Pointer<dxBody> Function(ffi.Pointer<dxWorld>)>();

  /// Destroy a body.
  void dBodyDestroy(ffi.Pointer<dxBody> arg0) {
    return _dBodyDestroy(arg0);
  }

  late final _dBodyDestroyPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Pointer<dxBody>)>>(
        'dBodyDestroy',
      );
  late final _dBodyDestroy = _dBodyDestroyPtr
      .asFunction<void Function(ffi.Pointer<dxBody>)>();

  /// Set position of a body.
  void dBodySetPosition(
    ffi.Pointer<dxBody> arg0,
    double x,
    double y,
    double z,
  ) {
    return _dBodySetPosition(arg0, x, y, z);
  }

  late final _dBodySetPositionPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Void Function(ffi.Pointer<dxBody>, dReal, dReal, dReal)
        >
      >('dBodySetPosition');
  late final _dBodySetPosition = _dBodySetPositionPtr
      .asFunction<void Function(ffi.Pointer<dxBody>, double, double, double)>();

  /// Set the orientation of a body.
  void dBodySetQuaternion(ffi.Pointer<dxBody> arg0, ffi.Pointer<dReal> q) {
    return _dBodySetQuaternion(arg0, q);
  }

  late final _dBodySetQuaternionPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Void Function(ffi.Pointer<dxBody>, ffi.Pointer<dReal>)
        >
      >('dBodySetQuaternion');
  late final _dBodySetQuaternion = _dBodySetQuaternionPtr
      .asFunction<void Function(ffi.Pointer<dxBody>, ffi.Pointer<dReal>)>();

  /// Set the linear velocity of a body.
  void dBodySetLinearVel(
    ffi.Pointer<dxBody> arg0,
    double x,
    double y,
    double z,
  ) {
    return _dBodySetLinearVel(arg0, x, y, z);
  }

  late final _dBodySetLinearVelPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Void Function(ffi.Pointer<dxBody>, dReal, dReal, dReal)
        >
      >('dBodySetLinearVel');
  late final _dBodySetLinearVel = _dBodySetLinearVelPtr
      .asFunction<void Function(ffi.Pointer<dxBody>, double, double, double)>();

  /// Set the angular velocity of a body.
  void dBodySetAngularVel(
    ffi.Pointer<dxBody> arg0,
    double x,
    double y,
    double z,
  ) {
    return _dBodySetAngularVel(arg0, x, y, z);
  }

  late final _dBodySetAngularVelPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Void Function(ffi.Pointer<dxBody>, dReal, dReal, dReal)
        >
      >('dBodySetAngularVel');
  late final _dBodySetAngularVel = _dBodySetAngularVelPtr
      .asFunction<void Function(ffi.Pointer<dxBody>, double, double, double)>();

  /// Get the position of a body.
  ffi.Pointer<dReal> dBodyGetPosition(ffi.Pointer<dxBody> arg0) {
    return _dBodyGetPosition(arg0);
  }

  late final _dBodyGetPositionPtr =
      _lookup<
        ffi.NativeFunction<ffi.Pointer<dReal> Function(ffi.Pointer<dxBody>)>
      >('dBodyGetPosition');
  late final _dBodyGetPosition = _dBodyGetPositionPtr
      .asFunction<ffi.Pointer<dReal> Function(ffi.Pointer<dxBody>)>();

  /// Get the rotation of a body.
  ffi.Pointer<dReal> dBodyGetQuaternion(ffi.Pointer<dxBody> arg0) {
    return _dBodyGetQuaternion(arg0);
  }

  late final _dBodyGetQuaternionPtr =
      _lookup<
        ffi.NativeFunction<ffi.Pointer<dReal> Function(ffi.Pointer<dxBody>)>
      >('dBodyGetQuaternion');
  late final _dBodyGetQuaternion = _dBodyGetQuaternionPtr
      .asFunction<ffi.Pointer<dReal> Function(ffi.Pointer<dxBody>)>();

  /// Get the linear velocity of a body.
  ffi.Pointer<dReal> dBodyGetLinearVel(ffi.Pointer<dxBody> arg0) {
    return _dBodyGetLinearVel(arg0);
  }

  late final _dBodyGetLinearVelPtr =
      _lookup<
        ffi.NativeFunction<ffi.Pointer<dReal> Function(ffi.Pointer<dxBody>)>
      >('dBodyGetLinearVel');
  late final _dBodyGetLinearVel = _dBodyGetLinearVelPtr
      .asFunction<ffi.Pointer<dReal> Function(ffi.Pointer<dxBody>)>();

  /// Get the angular velocity of a body.
  ffi.Pointer<dReal> dBodyGetAngularVel(ffi.Pointer<dxBody> arg0) {
    return _dBodyGetAngularVel(arg0);
  }

  late final _dBodyGetAngularVelPtr =
      _lookup<
        ffi.NativeFunction<ffi.Pointer<dReal> Function(ffi.Pointer<dxBody>)>
      >('dBodyGetAngularVel');
  late final _dBodyGetAngularVel = _dBodyGetAngularVelPtr
      .asFunction<ffi.Pointer<dReal> Function(ffi.Pointer<dxBody>)>();

  /// Set the mass of a body.
  void dBodySetMass(ffi.Pointer<dxBody> arg0, ffi.Pointer<dMass> mass) {
    return _dBodySetMass(arg0, mass);
  }

  late final _dBodySetMassPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Void Function(ffi.Pointer<dxBody>, ffi.Pointer<dMass>)
        >
      >('dBodySetMass');
  late final _dBodySetMass = _dBodySetMassPtr
      .asFunction<void Function(ffi.Pointer<dxBody>, ffi.Pointer<dMass>)>();

  /// Get the mass of a body.
  void dBodyGetMass(ffi.Pointer<dxBody> arg0, ffi.Pointer<dMass> mass) {
    return _dBodyGetMass(arg0, mass);
  }

  late final _dBodyGetMassPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Void Function(ffi.Pointer<dxBody>, ffi.Pointer<dMass>)
        >
      >('dBodyGetMass');
  late final _dBodyGetMass = _dBodyGetMassPtr
      .asFunction<void Function(ffi.Pointer<dxBody>, ffi.Pointer<dMass>)>();

  /// Add force at centre of mass of body in absolute coordinates.
  void dBodyAddForce(
    ffi.Pointer<dxBody> arg0,
    double fx,
    double fy,
    double fz,
  ) {
    return _dBodyAddForce(arg0, fx, fy, fz);
  }

  late final _dBodyAddForcePtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Void Function(ffi.Pointer<dxBody>, dReal, dReal, dReal)
        >
      >('dBodyAddForce');
  late final _dBodyAddForce = _dBodyAddForcePtr
      .asFunction<void Function(ffi.Pointer<dxBody>, double, double, double)>();

  /// Add torque at centre of mass of body in absolute coordinates.
  void dBodyAddTorque(
    ffi.Pointer<dxBody> arg0,
    double fx,
    double fy,
    double fz,
  ) {
    return _dBodyAddTorque(arg0, fx, fy, fz);
  }

  late final _dBodyAddTorquePtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Void Function(ffi.Pointer<dxBody>, dReal, dReal, dReal)
        >
      >('dBodyAddTorque');
  late final _dBodyAddTorque = _dBodyAddTorquePtr
      .asFunction<void Function(ffi.Pointer<dxBody>, double, double, double)>();

  /// Add force at specified point in body in global coordinates.
  void dBodyAddForceAtPos(
    ffi.Pointer<dxBody> arg0,
    double fx,
    double fy,
    double fz,
    double px,
    double py,
    double pz,
  ) {
    return _dBodyAddForceAtPos(arg0, fx, fy, fz, px, py, pz);
  }

  late final _dBodyAddForceAtPosPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Void Function(
            ffi.Pointer<dxBody>,
            dReal,
            dReal,
            dReal,
            dReal,
            dReal,
            dReal,
          )
        >
      >('dBodyAddForceAtPos');
  late final _dBodyAddForceAtPos = _dBodyAddForceAtPosPtr
      .asFunction<
        void Function(
          ffi.Pointer<dxBody>,
          double,
          double,
          double,
          double,
          double,
          double,
        )
      >();

  /// Set the body force accumulation vector.
  void dBodySetForce(ffi.Pointer<dxBody> b, double x, double y, double z) {
    return _dBodySetForce(b, x, y, z);
  }

  late final _dBodySetForcePtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Void Function(ffi.Pointer<dxBody>, dReal, dReal, dReal)
        >
      >('dBodySetForce');
  late final _dBodySetForce = _dBodySetForcePtr
      .asFunction<void Function(ffi.Pointer<dxBody>, double, double, double)>();

  /// Set the body torque accumulation vector.
  void dBodySetTorque(ffi.Pointer<dxBody> b, double x, double y, double z) {
    return _dBodySetTorque(b, x, y, z);
  }

  late final _dBodySetTorquePtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Void Function(ffi.Pointer<dxBody>, dReal, dReal, dReal)
        >
      >('dBodySetTorque');
  late final _dBodySetTorque = _dBodySetTorquePtr
      .asFunction<void Function(ffi.Pointer<dxBody>, double, double, double)>();

  /// Set rigid body to dynamic state (default).
  void dBodySetDynamic(ffi.Pointer<dxBody> arg0) {
    return _dBodySetDynamic(arg0);
  }

  late final _dBodySetDynamicPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Pointer<dxBody>)>>(
        'dBodySetDynamic',
      );
  late final _dBodySetDynamic = _dBodySetDynamicPtr
      .asFunction<void Function(ffi.Pointer<dxBody>)>();

  /// Set rigid body to kinematic state. When in kinematic state the body isn't
  /// simulated as a dynamic body (it's "unstoppable", doesn't respond to
  /// forces), but can still affect dynamic bodies (e.g. in joints). Kinematic
  /// bodies can be controlled by position and velocity.
  void dBodySetKinematic(ffi.Pointer<dxBody> arg0) {
    return _dBodySetKinematic(arg0);
  }

  late final _dBodySetKinematicPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Pointer<dxBody>)>>(
        'dBodySetKinematic',
      );
  late final _dBodySetKinematic = _dBodySetKinematicPtr
      .asFunction<void Function(ffi.Pointer<dxBody>)>();

  /// Manually enable a body.
  void dBodyEnable(ffi.Pointer<dxBody> arg0) {
    return _dBodyEnable(arg0);
  }

  late final _dBodyEnablePtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Pointer<dxBody>)>>(
        'dBodyEnable',
      );
  late final _dBodyEnable = _dBodyEnablePtr
      .asFunction<void Function(ffi.Pointer<dxBody>)>();

  /// Manually disable a body.
  void dBodyDisable(ffi.Pointer<dxBody> arg0) {
    return _dBodyDisable(arg0);
  }

  late final _dBodyDisablePtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Pointer<dxBody>)>>(
        'dBodyDisable',
      );
  late final _dBodyDisable = _dBodyDisablePtr
      .asFunction<void Function(ffi.Pointer<dxBody>)>();

  /// Check wether a body is enabled.
  int dBodyIsEnabled(ffi.Pointer<dxBody> arg0) {
    return _dBodyIsEnabled(arg0);
  }

  late final _dBodyIsEnabledPtr =
      _lookup<ffi.NativeFunction<ffi.Int Function(ffi.Pointer<dxBody>)>>(
        'dBodyIsEnabled',
      );
  late final _dBodyIsEnabled = _dBodyIsEnabledPtr
      .asFunction<int Function(ffi.Pointer<dxBody>)>();

  /// Set whether the body is influenced by the world's gravity or not.
  void dBodySetGravityMode(ffi.Pointer<dxBody> b, int mode) {
    return _dBodySetGravityMode(b, mode);
  }

  late final _dBodySetGravityModePtr =
      _lookup<
        ffi.NativeFunction<ffi.Void Function(ffi.Pointer<dxBody>, ffi.Int)>
      >('dBodySetGravityMode');
  late final _dBodySetGravityMode = _dBodySetGravityModePtr
      .asFunction<void Function(ffi.Pointer<dxBody>, int)>();

  /// Set the body's linear damping scale.
  void dBodySetLinearDamping(ffi.Pointer<dxBody> b, double scale) {
    return _dBodySetLinearDamping(b, scale);
  }

  late final _dBodySetLinearDampingPtr =
      _lookup<
        ffi.NativeFunction<ffi.Void Function(ffi.Pointer<dxBody>, dReal)>
      >('dBodySetLinearDamping');
  late final _dBodySetLinearDamping = _dBodySetLinearDampingPtr
      .asFunction<void Function(ffi.Pointer<dxBody>, double)>();

  /// Set the body's angular damping scale.
  void dBodySetAngularDamping(ffi.Pointer<dxBody> b, double scale) {
    return _dBodySetAngularDamping(b, scale);
  }

  late final _dBodySetAngularDampingPtr =
      _lookup<
        ffi.NativeFunction<ffi.Void Function(ffi.Pointer<dxBody>, dReal)>
      >('dBodySetAngularDamping');
  late final _dBodySetAngularDamping = _dBodySetAngularDampingPtr
      .asFunction<void Function(ffi.Pointer<dxBody>, double)>();

  /// Create a new joint of the hinge type.
  ffi.Pointer<dxJoint> dJointCreateHinge(
    ffi.Pointer<dxWorld> arg0,
    ffi.Pointer<dxJointGroup> arg1,
  ) {
    return _dJointCreateHinge(arg0, arg1);
  }

  late final _dJointCreateHingePtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Pointer<dxJoint> Function(
            ffi.Pointer<dxWorld>,
            ffi.Pointer<dxJointGroup>,
          )
        >
      >('dJointCreateHinge');
  late final _dJointCreateHinge = _dJointCreateHingePtr
      .asFunction<
        ffi.Pointer<dxJoint> Function(
          ffi.Pointer<dxWorld>,
          ffi.Pointer<dxJointGroup>,
        )
      >();

  /// Create a new joint of the contact type.
  ffi.Pointer<dxJoint> dJointCreateContact(
    ffi.Pointer<dxWorld> arg0,
    ffi.Pointer<dxJointGroup> arg1,
    ffi.Pointer<dContact> arg2,
  ) {
    return _dJointCreateContact(arg0, arg1, arg2);
  }

  late final _dJointCreateContactPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Pointer<dxJoint> Function(
            ffi.Pointer<dxWorld>,
            ffi.Pointer<dxJointGroup>,
            ffi.Pointer<dContact>,
          )
        >
      >('dJointCreateContact');
  late final _dJointCreateContact = _dJointCreateContactPtr
      .asFunction<
        ffi.Pointer<dxJoint> Function(
          ffi.Pointer<dxWorld>,
          ffi.Pointer<dxJointGroup>,
          ffi.Pointer<dContact>,
        )
      >();

  /// Create a new joint of the fixed type.
  ffi.Pointer<dxJoint> dJointCreateFixed(
    ffi.Pointer<dxWorld> arg0,
    ffi.Pointer<dxJointGroup> arg1,
  ) {
    return _dJointCreateFixed(arg0, arg1);
  }

  late final _dJointCreateFixedPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Pointer<dxJoint> Function(
            ffi.Pointer<dxWorld>,
            ffi.Pointer<dxJointGroup>,
          )
        >
      >('dJointCreateFixed');
  late final _dJointCreateFixed = _dJointCreateFixedPtr
      .asFunction<
        ffi.Pointer<dxJoint> Function(
          ffi.Pointer<dxWorld>,
          ffi.Pointer<dxJointGroup>,
        )
      >();

  /// Destroy a joint.
  void dJointDestroy(ffi.Pointer<dxJoint> arg0) {
    return _dJointDestroy(arg0);
  }

  late final _dJointDestroyPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Pointer<dxJoint>)>>(
        'dJointDestroy',
      );
  late final _dJointDestroy = _dJointDestroyPtr
      .asFunction<void Function(ffi.Pointer<dxJoint>)>();

  /// Create a joint group
  ffi.Pointer<dxJointGroup> dJointGroupCreate(int max_size) {
    return _dJointGroupCreate(max_size);
  }

  late final _dJointGroupCreatePtr =
      _lookup<ffi.NativeFunction<ffi.Pointer<dxJointGroup> Function(ffi.Int)>>(
        'dJointGroupCreate',
      );
  late final _dJointGroupCreate = _dJointGroupCreatePtr
      .asFunction<ffi.Pointer<dxJointGroup> Function(int)>();

  /// Destroy a joint group.
  void dJointGroupDestroy(ffi.Pointer<dxJointGroup> arg0) {
    return _dJointGroupDestroy(arg0);
  }

  late final _dJointGroupDestroyPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Pointer<dxJointGroup>)>>(
        'dJointGroupDestroy',
      );
  late final _dJointGroupDestroy = _dJointGroupDestroyPtr
      .asFunction<void Function(ffi.Pointer<dxJointGroup>)>();

  /// Empty a joint group.
  void dJointGroupEmpty(ffi.Pointer<dxJointGroup> arg0) {
    return _dJointGroupEmpty(arg0);
  }

  late final _dJointGroupEmptyPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Pointer<dxJointGroup>)>>(
        'dJointGroupEmpty',
      );
  late final _dJointGroupEmpty = _dJointGroupEmptyPtr
      .asFunction<void Function(ffi.Pointer<dxJointGroup>)>();

  /// Attach the joint to some new bodies.
  void dJointAttach(
    ffi.Pointer<dxJoint> arg0,
    ffi.Pointer<dxBody> body1,
    ffi.Pointer<dxBody> body2,
  ) {
    return _dJointAttach(arg0, body1, body2);
  }

  late final _dJointAttachPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Void Function(
            ffi.Pointer<dxJoint>,
            ffi.Pointer<dxBody>,
            ffi.Pointer<dxBody>,
          )
        >
      >('dJointAttach');
  late final _dJointAttach = _dJointAttachPtr
      .asFunction<
        void Function(
          ffi.Pointer<dxJoint>,
          ffi.Pointer<dxBody>,
          ffi.Pointer<dxBody>,
        )
      >();

  /// Set hinge anchor parameter.
  void dJointSetHingeAnchor(
    ffi.Pointer<dxJoint> arg0,
    double x,
    double y,
    double z,
  ) {
    return _dJointSetHingeAnchor(arg0, x, y, z);
  }

  late final _dJointSetHingeAnchorPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Void Function(ffi.Pointer<dxJoint>, dReal, dReal, dReal)
        >
      >('dJointSetHingeAnchor');
  late final _dJointSetHingeAnchor = _dJointSetHingeAnchorPtr
      .asFunction<
        void Function(ffi.Pointer<dxJoint>, double, double, double)
      >();

  /// Set hinge axis.
  void dJointSetHingeAxis(
    ffi.Pointer<dxJoint> arg0,
    double x,
    double y,
    double z,
  ) {
    return _dJointSetHingeAxis(arg0, x, y, z);
  }

  late final _dJointSetHingeAxisPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Void Function(ffi.Pointer<dxJoint>, dReal, dReal, dReal)
        >
      >('dJointSetHingeAxis');
  late final _dJointSetHingeAxis = _dJointSetHingeAxisPtr
      .asFunction<
        void Function(ffi.Pointer<dxJoint>, double, double, double)
      >();

  /// set joint parameter
  void dJointSetHingeParam(
    ffi.Pointer<dxJoint> arg0,
    int parameter,
    double value,
  ) {
    return _dJointSetHingeParam(arg0, parameter, value);
  }

  late final _dJointSetHingeParamPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Void Function(ffi.Pointer<dxJoint>, ffi.Int, dReal)
        >
      >('dJointSetHingeParam');
  late final _dJointSetHingeParam = _dJointSetHingeParamPtr
      .asFunction<void Function(ffi.Pointer<dxJoint>, int, double)>();

  /// Call this on the fixed joint after it has been attached to remember the
  /// current desired relative offset and desired relative rotation between the
  /// bodies.
  void dJointSetFixed(ffi.Pointer<dxJoint> arg0) {
    return _dJointSetFixed(arg0);
  }

  late final _dJointSetFixedPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Pointer<dxJoint>)>>(
        'dJointSetFixed',
      );
  late final _dJointSetFixed = _dJointSetFixedPtr
      .asFunction<void Function(ffi.Pointer<dxJoint>)>();

  /// Get the hinge anchor point, in world coordinates.
  void dJointGetHingeAnchor(
    ffi.Pointer<dxJoint> arg0,
    ffi.Pointer<dReal> result,
  ) {
    return _dJointGetHingeAnchor(arg0, result);
  }

  late final _dJointGetHingeAnchorPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Void Function(ffi.Pointer<dxJoint>, ffi.Pointer<dReal>)
        >
      >('dJointGetHingeAnchor');
  late final _dJointGetHingeAnchor = _dJointGetHingeAnchorPtr
      .asFunction<void Function(ffi.Pointer<dxJoint>, ffi.Pointer<dReal>)>();

  /// Get the joint anchor point, in world coordinates.
  void dJointGetHingeAnchor2(
    ffi.Pointer<dxJoint> arg0,
    ffi.Pointer<dReal> result,
  ) {
    return _dJointGetHingeAnchor2(arg0, result);
  }

  late final _dJointGetHingeAnchor2Ptr =
      _lookup<
        ffi.NativeFunction<
          ffi.Void Function(ffi.Pointer<dxJoint>, ffi.Pointer<dReal>)
        >
      >('dJointGetHingeAnchor2');
  late final _dJointGetHingeAnchor2 = _dJointGetHingeAnchor2Ptr
      .asFunction<void Function(ffi.Pointer<dxJoint>, ffi.Pointer<dReal>)>();

  /// Get the hinge angle.
  double dJointGetHingeAngle(ffi.Pointer<dxJoint> arg0) {
    return _dJointGetHingeAngle(arg0);
  }

  late final _dJointGetHingeAnglePtr =
      _lookup<ffi.NativeFunction<dReal Function(ffi.Pointer<dxJoint>)>>(
        'dJointGetHingeAngle',
      );
  late final _dJointGetHingeAngle = _dJointGetHingeAnglePtr
      .asFunction<double Function(ffi.Pointer<dxJoint>)>();

  /// Get the hinge angle time derivative.
  double dJointGetHingeAngleRate(ffi.Pointer<dxJoint> arg0) {
    return _dJointGetHingeAngleRate(arg0);
  }

  late final _dJointGetHingeAngleRatePtr =
      _lookup<ffi.NativeFunction<dReal Function(ffi.Pointer<dxJoint>)>>(
        'dJointGetHingeAngleRate',
      );
  late final _dJointGetHingeAngleRate = _dJointGetHingeAngleRatePtr
      .asFunction<double Function(ffi.Pointer<dxJoint>)>();

  /// Utility function
  int dAreConnectedExcluding(
    ffi.Pointer<dxBody> body1,
    ffi.Pointer<dxBody> body2,
    int joint_type,
  ) {
    return _dAreConnectedExcluding(body1, body2, joint_type);
  }

  late final _dAreConnectedExcludingPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Int Function(ffi.Pointer<dxBody>, ffi.Pointer<dxBody>, ffi.Int)
        >
      >('dAreConnectedExcluding');
  late final _dAreConnectedExcluding = _dAreConnectedExcludingPtr
      .asFunction<
        int Function(ffi.Pointer<dxBody>, ffi.Pointer<dxBody>, int)
      >();

  ffi.Pointer<dxSpace> dHashSpaceCreate(ffi.Pointer<dxSpace> space) {
    return _dHashSpaceCreate(space);
  }

  late final _dHashSpaceCreatePtr =
      _lookup<
        ffi.NativeFunction<ffi.Pointer<dxSpace> Function(ffi.Pointer<dxSpace>)>
      >('dHashSpaceCreate');
  late final _dHashSpaceCreate = _dHashSpaceCreatePtr
      .asFunction<ffi.Pointer<dxSpace> Function(ffi.Pointer<dxSpace>)>();

  void dSpaceDestroy(ffi.Pointer<dxSpace> arg0) {
    return _dSpaceDestroy(arg0);
  }

  late final _dSpaceDestroyPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Pointer<dxSpace>)>>(
        'dSpaceDestroy',
      );
  late final _dSpaceDestroy = _dSpaceDestroyPtr
      .asFunction<void Function(ffi.Pointer<dxSpace>)>();

  /// Destroy a geom, removing it from any space.
  void dGeomDestroy(ffi.Pointer<dxGeom> geom) {
    return _dGeomDestroy(geom);
  }

  late final _dGeomDestroyPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Pointer<dxGeom>)>>(
        'dGeomDestroy',
      );
  late final _dGeomDestroy = _dGeomDestroyPtr
      .asFunction<void Function(ffi.Pointer<dxGeom>)>();

  /// Set the body associated with a placeable geom.
  void dGeomSetBody(ffi.Pointer<dxGeom> geom, ffi.Pointer<dxBody> body) {
    return _dGeomSetBody(geom, body);
  }

  late final _dGeomSetBodyPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Void Function(ffi.Pointer<dxGeom>, ffi.Pointer<dxBody>)
        >
      >('dGeomSetBody');
  late final _dGeomSetBody = _dGeomSetBodyPtr
      .asFunction<void Function(ffi.Pointer<dxGeom>, ffi.Pointer<dxBody>)>();

  /// Get the body associated with a placeable geom.
  ffi.Pointer<dxBody> dGeomGetBody(ffi.Pointer<dxGeom> geom) {
    return _dGeomGetBody(geom);
  }

  late final _dGeomGetBodyPtr =
      _lookup<
        ffi.NativeFunction<ffi.Pointer<dxBody> Function(ffi.Pointer<dxGeom>)>
      >('dGeomGetBody');
  late final _dGeomGetBody = _dGeomGetBodyPtr
      .asFunction<ffi.Pointer<dxBody> Function(ffi.Pointer<dxGeom>)>();

  /// Set the position vector of a placeable geom.
  void dGeomSetPosition(
    ffi.Pointer<dxGeom> geom,
    double x,
    double y,
    double z,
  ) {
    return _dGeomSetPosition(geom, x, y, z);
  }

  late final _dGeomSetPositionPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Void Function(ffi.Pointer<dxGeom>, dReal, dReal, dReal)
        >
      >('dGeomSetPosition');
  late final _dGeomSetPosition = _dGeomSetPositionPtr
      .asFunction<void Function(ffi.Pointer<dxGeom>, double, double, double)>();

  /// Set the rotation of a placeable geom.
  void dGeomSetQuaternion(ffi.Pointer<dxGeom> geom, ffi.Pointer<dReal> Q) {
    return _dGeomSetQuaternion(geom, Q);
  }

  late final _dGeomSetQuaternionPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Void Function(ffi.Pointer<dxGeom>, ffi.Pointer<dReal>)
        >
      >('dGeomSetQuaternion');
  late final _dGeomSetQuaternion = _dGeomSetQuaternionPtr
      .asFunction<void Function(ffi.Pointer<dxGeom>, ffi.Pointer<dReal>)>();

  /// Set the local offset position of a geom from its body.
  void dGeomSetOffsetPosition(
    ffi.Pointer<dxGeom> geom,
    double x,
    double y,
    double z,
  ) {
    return _dGeomSetOffsetPosition(geom, x, y, z);
  }

  late final _dGeomSetOffsetPositionPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Void Function(ffi.Pointer<dxGeom>, dReal, dReal, dReal)
        >
      >('dGeomSetOffsetPosition');
  late final _dGeomSetOffsetPosition = _dGeomSetOffsetPositionPtr
      .asFunction<void Function(ffi.Pointer<dxGeom>, double, double, double)>();

  /// Set the local offset rotation of a geom from its body.
  void dGeomSetOffsetQuaternion(
    ffi.Pointer<dxGeom> geom,
    ffi.Pointer<dReal> Q,
  ) {
    return _dGeomSetOffsetQuaternion(geom, Q);
  }

  late final _dGeomSetOffsetQuaternionPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Void Function(ffi.Pointer<dxGeom>, ffi.Pointer<dReal>)
        >
      >('dGeomSetOffsetQuaternion');
  late final _dGeomSetOffsetQuaternion = _dGeomSetOffsetQuaternionPtr
      .asFunction<void Function(ffi.Pointer<dxGeom>, ffi.Pointer<dReal>)>();

  /// Given two geoms o1 and o2 that potentially intersect, generate contact
  /// information for them.
  int dCollide(
    ffi.Pointer<dxGeom> o1,
    ffi.Pointer<dxGeom> o2,
    int flags,
    ffi.Pointer<dContactGeom> contact,
    int skip,
  ) {
    return _dCollide(o1, o2, flags, contact, skip);
  }

  late final _dCollidePtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Int Function(
            ffi.Pointer<dxGeom>,
            ffi.Pointer<dxGeom>,
            ffi.Int,
            ffi.Pointer<dContactGeom>,
            ffi.Int,
          )
        >
      >('dCollide');
  late final _dCollide = _dCollidePtr
      .asFunction<
        int Function(
          ffi.Pointer<dxGeom>,
          ffi.Pointer<dxGeom>,
          int,
          ffi.Pointer<dContactGeom>,
          int,
        )
      >();

  /// Determines which pairs of geoms in a space may potentially intersect, and
  /// calls the callback function for each candidate pair.
  void dSpaceCollide(
    ffi.Pointer<dxSpace> space,
    ffi.Pointer<ffi.Void> data,
    ffi.Pointer<dNearCallback> callback,
  ) {
    return _dSpaceCollide(space, data, callback);
  }

  late final _dSpaceCollidePtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Void Function(
            ffi.Pointer<dxSpace>,
            ffi.Pointer<ffi.Void>,
            ffi.Pointer<dNearCallback>,
          )
        >
      >('dSpaceCollide');
  late final _dSpaceCollide = _dSpaceCollidePtr
      .asFunction<
        void Function(
          ffi.Pointer<dxSpace>,
          ffi.Pointer<ffi.Void>,
          ffi.Pointer<dNearCallback>,
        )
      >();

  /// Create a sphere geom of the given radius, and return its ID.
  ffi.Pointer<dxGeom> dCreateSphere(ffi.Pointer<dxSpace> space, double radius) {
    return _dCreateSphere(space, radius);
  }

  late final _dCreateSpherePtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Pointer<dxGeom> Function(ffi.Pointer<dxSpace>, dReal)
        >
      >('dCreateSphere');
  late final _dCreateSphere = _dCreateSpherePtr
      .asFunction<ffi.Pointer<dxGeom> Function(ffi.Pointer<dxSpace>, double)>();

  /// Create a box geom with the provided side lengths.
  ffi.Pointer<dxGeom> dCreateBox(
    ffi.Pointer<dxSpace> space,
    double lx,
    double ly,
    double lz,
  ) {
    return _dCreateBox(space, lx, ly, lz);
  }

  late final _dCreateBoxPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Pointer<dxGeom> Function(
            ffi.Pointer<dxSpace>,
            dReal,
            dReal,
            dReal,
          )
        >
      >('dCreateBox');
  late final _dCreateBox = _dCreateBoxPtr
      .asFunction<
        ffi.Pointer<dxGeom> Function(
          ffi.Pointer<dxSpace>,
          double,
          double,
          double,
        )
      >();

  ffi.Pointer<dxGeom> dCreatePlane(
    ffi.Pointer<dxSpace> space,
    double a,
    double b,
    double c,
    double d,
  ) {
    return _dCreatePlane(space, a, b, c, d);
  }

  late final _dCreatePlanePtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Pointer<dxGeom> Function(
            ffi.Pointer<dxSpace>,
            dReal,
            dReal,
            dReal,
            dReal,
          )
        >
      >('dCreatePlane');
  late final _dCreatePlane = _dCreatePlanePtr
      .asFunction<
        ffi.Pointer<dxGeom> Function(
          ffi.Pointer<dxSpace>,
          double,
          double,
          double,
          double,
        )
      >();

  ffi.Pointer<dxGeom> dCreateCylinder(
    ffi.Pointer<dxSpace> space,
    double radius,
    double length,
  ) {
    return _dCreateCylinder(space, radius, length);
  }

  late final _dCreateCylinderPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Pointer<dxGeom> Function(ffi.Pointer<dxSpace>, dReal, dReal)
        >
      >('dCreateCylinder');
  late final _dCreateCylinder = _dCreateCylinderPtr
      .asFunction<
        ffi.Pointer<dxGeom> Function(ffi.Pointer<dxSpace>, double, double)
      >();

  void dGeomCylinderSetParams(
    ffi.Pointer<dxGeom> cylinder,
    double radius,
    double length,
  ) {
    return _dGeomCylinderSetParams(cylinder, radius, length);
  }

  late final _dGeomCylinderSetParamsPtr =
      _lookup<
        ffi.NativeFunction<ffi.Void Function(ffi.Pointer<dxGeom>, dReal, dReal)>
      >('dGeomCylinderSetParams');
  late final _dGeomCylinderSetParams = _dGeomCylinderSetParamsPtr
      .asFunction<void Function(ffi.Pointer<dxGeom>, double, double)>();

  void dGeomCylinderGetParams(
    ffi.Pointer<dxGeom> cylinder,
    ffi.Pointer<dReal> radius,
    ffi.Pointer<dReal> length,
  ) {
    return _dGeomCylinderGetParams(cylinder, radius, length);
  }

  late final _dGeomCylinderGetParamsPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Void Function(
            ffi.Pointer<dxGeom>,
            ffi.Pointer<dReal>,
            ffi.Pointer<dReal>,
          )
        >
      >('dGeomCylinderGetParams');
  late final _dGeomCylinderGetParams = _dGeomCylinderGetParamsPtr
      .asFunction<
        void Function(
          ffi.Pointer<dxGeom>,
          ffi.Pointer<dReal>,
          ffi.Pointer<dReal>,
        )
      >();

  ffi.Pointer<dxGeom> dCreateRay(ffi.Pointer<dxSpace> space, double length) {
    return _dCreateRay(space, length);
  }

  late final _dCreateRayPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Pointer<dxGeom> Function(ffi.Pointer<dxSpace>, dReal)
        >
      >('dCreateRay');
  late final _dCreateRay = _dCreateRayPtr
      .asFunction<ffi.Pointer<dxGeom> Function(ffi.Pointer<dxSpace>, double)>();

  void dGeomRaySetLength(ffi.Pointer<dxGeom> ray, double length) {
    return _dGeomRaySetLength(ray, length);
  }

  late final _dGeomRaySetLengthPtr =
      _lookup<
        ffi.NativeFunction<ffi.Void Function(ffi.Pointer<dxGeom>, dReal)>
      >('dGeomRaySetLength');
  late final _dGeomRaySetLength = _dGeomRaySetLengthPtr
      .asFunction<void Function(ffi.Pointer<dxGeom>, double)>();

  void dGeomRaySet(
    ffi.Pointer<dxGeom> ray,
    double px,
    double py,
    double pz,
    double dx,
    double dy,
    double dz,
  ) {
    return _dGeomRaySet(ray, px, py, pz, dx, dy, dz);
  }

  late final _dGeomRaySetPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Void Function(
            ffi.Pointer<dxGeom>,
            dReal,
            dReal,
            dReal,
            dReal,
            dReal,
            dReal,
          )
        >
      >('dGeomRaySet');
  late final _dGeomRaySet = _dGeomRaySetPtr
      .asFunction<
        void Function(
          ffi.Pointer<dxGeom>,
          double,
          double,
          double,
          double,
          double,
          double,
        )
      >();
}

final class _IO_FILE extends ffi.Opaque {}

final class UnnamedStruct extends ffi.Struct {
  @ffi.UnsignedInt()
  external int __low;

  @ffi.UnsignedInt()
  external int __high;
}

final class __atomic_wide_counter extends ffi.Union {
  @ffi.UnsignedLongLong()
  external int __value64;

  external UnnamedStruct __value32;
}

final class __pthread_internal_list extends ffi.Struct {
  external ffi.Pointer<__pthread_internal_list> __prev;

  external ffi.Pointer<__pthread_internal_list> __next;
}

final class __pthread_mutex_s extends ffi.Struct {
  @ffi.Int()
  external int __lock;

  @ffi.UnsignedInt()
  external int __count;

  @ffi.Int()
  external int __owner;

  @ffi.UnsignedInt()
  external int __nusers;

  @ffi.Int()
  external int __kind;

  @ffi.Int()
  external int __spins;

  external __pthread_internal_list __list;
}

final class __pthread_rwlock_arch_t extends ffi.Struct {
  @ffi.UnsignedInt()
  external int __readers;

  @ffi.UnsignedInt()
  external int __writers;

  @ffi.UnsignedInt()
  external int __wrphase_futex;

  @ffi.UnsignedInt()
  external int __writers_futex;

  @ffi.UnsignedInt()
  external int __pad3;

  @ffi.UnsignedInt()
  external int __pad4;

  @ffi.Int()
  external int __cur_writer;

  @ffi.Int()
  external int __shared;

  @ffi.UnsignedLong()
  external int __pad1;

  @ffi.UnsignedLong()
  external int __pad2;

  @ffi.UnsignedInt()
  external int __flags;
}

final class __pthread_cond_s extends ffi.Struct {
  external __atomic_wide_counter __wseq;

  external __atomic_wide_counter __g1_start;

  @ffi.Array.multi([2])
  external ffi.Array<ffi.UnsignedInt> __g_size;

  @ffi.UnsignedInt()
  external int __g1_orig_size;

  @ffi.UnsignedInt()
  external int __wrefs;

  @ffi.Array.multi([2])
  external ffi.Array<ffi.UnsignedInt> __g_signals;

  @ffi.UnsignedInt()
  external int __unused_initialized_1;

  @ffi.UnsignedInt()
  external int __unused_initialized_2;
}

final class pthread_mutexattr_t extends ffi.Union {
  @ffi.Array.multi([8])
  external ffi.Array<ffi.Char> __size;

  @ffi.Int()
  external int __align;
}

final class pthread_condattr_t extends ffi.Union {
  @ffi.Array.multi([8])
  external ffi.Array<ffi.Char> __size;

  @ffi.Int()
  external int __align;
}

final class pthread_attr_t extends ffi.Union {
  @ffi.Array.multi([64])
  external ffi.Array<ffi.Char> __size;

  @ffi.Long()
  external int __align;
}

final class pthread_mutex_t extends ffi.Union {
  external __pthread_mutex_s __data;

  @ffi.Array.multi([48])
  external ffi.Array<ffi.Char> __size;

  @ffi.Long()
  external int __align;
}

final class pthread_cond_t extends ffi.Union {
  external __pthread_cond_s __data;

  @ffi.Array.multi([48])
  external ffi.Array<ffi.Char> __size;

  @ffi.LongLong()
  external int __align;
}

final class pthread_rwlock_t extends ffi.Union {
  external __pthread_rwlock_arch_t __data;

  @ffi.Array.multi([56])
  external ffi.Array<ffi.Char> __size;

  @ffi.Long()
  external int __align;
}

final class pthread_rwlockattr_t extends ffi.Union {
  @ffi.Array.multi([8])
  external ffi.Array<ffi.Char> __size;

  @ffi.Long()
  external int __align;
}

final class pthread_barrier_t extends ffi.Union {
  @ffi.Array.multi([32])
  external ffi.Array<ffi.Char> __size;

  @ffi.Long()
  external int __align;
}

final class pthread_barrierattr_t extends ffi.Union {
  @ffi.Array.multi([8])
  external ffi.Array<ffi.Char> __size;

  @ffi.Int()
  external int __align;
}

typedef dReal = ffi.Float;
typedef DartdReal = double;

enum dSpaceAxis {
  dSA__MIN(0),
  dSA_Y(1),
  dSA_Z(2),
  dSA__MAX(3);

  static const dSA_X = dSA__MIN;

  final int value;
  const dSpaceAxis(this.value);

  static dSpaceAxis fromValue(int value) => switch (value) {
    0 => dSA__MIN,
    1 => dSA_Y,
    2 => dSA_Z,
    3 => dSA__MAX,
    _ => throw ArgumentError('Unknown value for dSpaceAxis: $value'),
  };

  @override
  String toString() {
    if (this == dSA__MIN) return "dSpaceAxis.dSA__MIN, dSpaceAxis.dSA_X";
    return super.toString();
  }
}

enum dMotionDynamics {
  dMD__MIN(0),
  dMD_ANGULAR(1),
  dMD__MAX(2);

  static const dMD_LINEAR = dMD__MIN;

  final int value;
  const dMotionDynamics(this.value);

  static dMotionDynamics fromValue(int value) => switch (value) {
    0 => dMD__MIN,
    1 => dMD_ANGULAR,
    2 => dMD__MAX,
    _ => throw ArgumentError('Unknown value for dMotionDynamics: $value'),
  };

  @override
  String toString() {
    if (this == dMD__MIN)
      return "dMotionDynamics.dMD__MIN, dMotionDynamics.dMD_LINEAR";
    return super.toString();
  }
}

enum dDynamicsAxis {
  dDA__MIN(0),
  dDA_LY(1),
  dDA_LZ(2),
  dDA__L_MAX(3),
  dDA_AY(4),
  dDA_AZ(5),
  dDA__A_MAX(6);

  static const dDA__L_MIN = dDA__MIN;
  static const dDA_LX = dDA__MIN;
  static const dDA__A_MIN = dDA__L_MAX;
  static const dDA_AX = dDA__L_MAX;
  static const dDA__MAX = dDA__A_MAX;

  final int value;
  const dDynamicsAxis(this.value);

  static dDynamicsAxis fromValue(int value) => switch (value) {
    0 => dDA__MIN,
    1 => dDA_LY,
    2 => dDA_LZ,
    3 => dDA__L_MAX,
    4 => dDA_AY,
    5 => dDA_AZ,
    6 => dDA__A_MAX,
    _ => throw ArgumentError('Unknown value for dDynamicsAxis: $value'),
  };

  @override
  String toString() {
    if (this == dDA__MIN)
      return "dDynamicsAxis.dDA__MIN, dDynamicsAxis.dDA__L_MIN, dDynamicsAxis.dDA_LX";
    if (this == dDA__L_MAX)
      return "dDynamicsAxis.dDA__L_MAX, dDynamicsAxis.dDA__A_MIN, dDynamicsAxis.dDA_AX";
    if (this == dDA__A_MAX)
      return "dDynamicsAxis.dDA__A_MAX, dDynamicsAxis.dDA__MAX";
    return super.toString();
  }
}

enum dVec3Element {
  dV3E__MIN(0),
  dV3E_Y(1),
  dV3E_Z(2),
  dV3E__AXES_MAX(3),
  dV3E__MAX(4);

  static const dV3E__AXES_MIN = dV3E__MIN;
  static const dV3E_X = dV3E__MIN;
  static const dV3E_PAD = dV3E__AXES_MAX;
  static const dV3E__AXES_COUNT = dV3E__AXES_MAX;

  final int value;
  const dVec3Element(this.value);

  static dVec3Element fromValue(int value) => switch (value) {
    0 => dV3E__MIN,
    1 => dV3E_Y,
    2 => dV3E_Z,
    3 => dV3E__AXES_MAX,
    4 => dV3E__MAX,
    _ => throw ArgumentError('Unknown value for dVec3Element: $value'),
  };

  @override
  String toString() {
    if (this == dV3E__MIN)
      return "dVec3Element.dV3E__MIN, dVec3Element.dV3E__AXES_MIN, dVec3Element.dV3E_X";
    if (this == dV3E__AXES_MAX)
      return "dVec3Element.dV3E__AXES_MAX, dVec3Element.dV3E_PAD, dVec3Element.dV3E__AXES_COUNT";
    return super.toString();
  }
}

enum dVec4Element {
  dV4E__MIN(0),
  dV4E_Y(1),
  dV4E_Z(2),
  dV4E_O(3),
  dV4E__MAX(4);

  static const dV4E_X = dV4E__MIN;

  final int value;
  const dVec4Element(this.value);

  static dVec4Element fromValue(int value) => switch (value) {
    0 => dV4E__MIN,
    1 => dV4E_Y,
    2 => dV4E_Z,
    3 => dV4E_O,
    4 => dV4E__MAX,
    _ => throw ArgumentError('Unknown value for dVec4Element: $value'),
  };

  @override
  String toString() {
    if (this == dV4E__MIN) return "dVec4Element.dV4E__MIN, dVec4Element.dV4E_X";
    return super.toString();
  }
}

enum dMat3Element {
  dM3E__MIN(0),
  dM3E_XY(1),
  dM3E_XZ(2),
  dM3E__X_AXES_MAX(3),
  dM3E__X_MAX(4),
  dM3E_YY(5),
  dM3E_YZ(6),
  dM3E__Y_AXES_MAX(7),
  dM3E__Y_MAX(8),
  dM3E_ZY(9),
  dM3E_ZZ(10),
  dM3E__Z_AXES_MAX(11),
  dM3E__Z_MAX(12);

  static const dM3E__X_MIN = dM3E__MIN;
  static const dM3E__X_AXES_MIN = dM3E__MIN;
  static const dM3E_XX = dM3E__MIN;
  static const dM3E_XPAD = dM3E__X_AXES_MAX;
  static const dM3E__Y_MIN = dM3E__X_MAX;
  static const dM3E__Y_AXES_MIN = dM3E__X_MAX;
  static const dM3E_YX = dM3E__X_MAX;
  static const dM3E_YPAD = dM3E__Y_AXES_MAX;
  static const dM3E__Z_MIN = dM3E__Y_MAX;
  static const dM3E__Z_AXES_MIN = dM3E__Y_MAX;
  static const dM3E_ZX = dM3E__Y_MAX;
  static const dM3E_ZPAD = dM3E__Z_AXES_MAX;
  static const dM3E__MAX = dM3E__Z_MAX;

  final int value;
  const dMat3Element(this.value);

  static dMat3Element fromValue(int value) => switch (value) {
    0 => dM3E__MIN,
    1 => dM3E_XY,
    2 => dM3E_XZ,
    3 => dM3E__X_AXES_MAX,
    4 => dM3E__X_MAX,
    5 => dM3E_YY,
    6 => dM3E_YZ,
    7 => dM3E__Y_AXES_MAX,
    8 => dM3E__Y_MAX,
    9 => dM3E_ZY,
    10 => dM3E_ZZ,
    11 => dM3E__Z_AXES_MAX,
    12 => dM3E__Z_MAX,
    _ => throw ArgumentError('Unknown value for dMat3Element: $value'),
  };

  @override
  String toString() {
    if (this == dM3E__MIN)
      return "dMat3Element.dM3E__MIN, dMat3Element.dM3E__X_MIN, dMat3Element.dM3E__X_AXES_MIN, dMat3Element.dM3E_XX";
    if (this == dM3E__X_AXES_MAX)
      return "dMat3Element.dM3E__X_AXES_MAX, dMat3Element.dM3E_XPAD";
    if (this == dM3E__X_MAX)
      return "dMat3Element.dM3E__X_MAX, dMat3Element.dM3E__Y_MIN, dMat3Element.dM3E__Y_AXES_MIN, dMat3Element.dM3E_YX";
    if (this == dM3E__Y_AXES_MAX)
      return "dMat3Element.dM3E__Y_AXES_MAX, dMat3Element.dM3E_YPAD";
    if (this == dM3E__Y_MAX)
      return "dMat3Element.dM3E__Y_MAX, dMat3Element.dM3E__Z_MIN, dMat3Element.dM3E__Z_AXES_MIN, dMat3Element.dM3E_ZX";
    if (this == dM3E__Z_AXES_MAX)
      return "dMat3Element.dM3E__Z_AXES_MAX, dMat3Element.dM3E_ZPAD";
    if (this == dM3E__Z_MAX)
      return "dMat3Element.dM3E__Z_MAX, dMat3Element.dM3E__MAX";
    return super.toString();
  }
}

enum dMat4Element {
  dM4E__MIN(0),
  dM4E_XY(1),
  dM4E_XZ(2),
  dM4E_XO(3),
  dM4E__X_MAX(4),
  dM4E_YY(5),
  dM4E_YZ(6),
  dM4E_YO(7),
  dM4E__Y_MAX(8),
  dM4E_ZY(9),
  dM4E_ZZ(10),
  dM4E_ZO(11),
  dM4E__Z_MAX(12),
  dM4E_OY(13),
  dM4E_OZ(14),
  dM4E_OO(15),
  dM4E__O_MAX(16);

  static const dM4E__X_MIN = dM4E__MIN;
  static const dM4E_XX = dM4E__MIN;
  static const dM4E__Y_MIN = dM4E__X_MAX;
  static const dM4E_YX = dM4E__X_MAX;
  static const dM4E__Z_MIN = dM4E__Y_MAX;
  static const dM4E_ZX = dM4E__Y_MAX;
  static const dM4E__O_MIN = dM4E__Z_MAX;
  static const dM4E_OX = dM4E__Z_MAX;
  static const dM4E__MAX = dM4E__O_MAX;

  final int value;
  const dMat4Element(this.value);

  static dMat4Element fromValue(int value) => switch (value) {
    0 => dM4E__MIN,
    1 => dM4E_XY,
    2 => dM4E_XZ,
    3 => dM4E_XO,
    4 => dM4E__X_MAX,
    5 => dM4E_YY,
    6 => dM4E_YZ,
    7 => dM4E_YO,
    8 => dM4E__Y_MAX,
    9 => dM4E_ZY,
    10 => dM4E_ZZ,
    11 => dM4E_ZO,
    12 => dM4E__Z_MAX,
    13 => dM4E_OY,
    14 => dM4E_OZ,
    15 => dM4E_OO,
    16 => dM4E__O_MAX,
    _ => throw ArgumentError('Unknown value for dMat4Element: $value'),
  };

  @override
  String toString() {
    if (this == dM4E__MIN)
      return "dMat4Element.dM4E__MIN, dMat4Element.dM4E__X_MIN, dMat4Element.dM4E_XX";
    if (this == dM4E__X_MAX)
      return "dMat4Element.dM4E__X_MAX, dMat4Element.dM4E__Y_MIN, dMat4Element.dM4E_YX";
    if (this == dM4E__Y_MAX)
      return "dMat4Element.dM4E__Y_MAX, dMat4Element.dM4E__Z_MIN, dMat4Element.dM4E_ZX";
    if (this == dM4E__Z_MAX)
      return "dMat4Element.dM4E__Z_MAX, dMat4Element.dM4E__O_MIN, dMat4Element.dM4E_OX";
    if (this == dM4E__O_MAX)
      return "dMat4Element.dM4E__O_MAX, dMat4Element.dM4E__MAX";
    return super.toString();
  }
}

enum dQuatElement {
  dQUE__MIN(0),
  dQUE__AXIS_MIN(1),
  dQUE_J(2),
  dQUE_K(3),
  dQUE__AXIS_MAX(4);

  static const dQUE_R = dQUE__MIN;
  static const dQUE_I = dQUE__AXIS_MIN;
  static const dQUE__MAX = dQUE__AXIS_MAX;

  final int value;
  const dQuatElement(this.value);

  static dQuatElement fromValue(int value) => switch (value) {
    0 => dQUE__MIN,
    1 => dQUE__AXIS_MIN,
    2 => dQUE_J,
    3 => dQUE_K,
    4 => dQUE__AXIS_MAX,
    _ => throw ArgumentError('Unknown value for dQuatElement: $value'),
  };

  @override
  String toString() {
    if (this == dQUE__MIN) return "dQuatElement.dQUE__MIN, dQuatElement.dQUE_R";
    if (this == dQUE__AXIS_MIN)
      return "dQuatElement.dQUE__AXIS_MIN, dQuatElement.dQUE_I";
    if (this == dQUE__AXIS_MAX)
      return "dQuatElement.dQUE__AXIS_MAX, dQuatElement.dQUE__MAX";
    return super.toString();
  }
}

/// internal object types (all prefixed with `dx')
final class dxWorld extends ffi.Opaque {}

final class dxSpace extends ffi.Opaque {}

final class dxBody extends ffi.Opaque {}

final class dxGeom extends ffi.Opaque {}

final class dxJoint extends ffi.Opaque {}

final class dxJointGroup extends ffi.Opaque {}

/// joint type numbers
enum dJointType {
  /// or "unknown"
  dJointTypeNone(0),
  dJointTypeBall(1),
  dJointTypeHinge(2),
  dJointTypeSlider(3),
  dJointTypeContact(4),
  dJointTypeUniversal(5),
  dJointTypeHinge2(6),
  dJointTypeFixed(7),
  dJointTypeNull(8),
  dJointTypeAMotor(9),
  dJointTypeLMotor(10),
  dJointTypePlane2D(11),
  dJointTypePR(12),
  dJointTypePU(13),
  dJointTypePiston(14),
  dJointTypeDBall(15),
  dJointTypeDHinge(16),
  dJointTypeTransmission(17);

  final int value;
  const dJointType(this.value);

  static dJointType fromValue(int value) => switch (value) {
    0 => dJointTypeNone,
    1 => dJointTypeBall,
    2 => dJointTypeHinge,
    3 => dJointTypeSlider,
    4 => dJointTypeContact,
    5 => dJointTypeUniversal,
    6 => dJointTypeHinge2,
    7 => dJointTypeFixed,
    8 => dJointTypeNull,
    9 => dJointTypeAMotor,
    10 => dJointTypeLMotor,
    11 => dJointTypePlane2D,
    12 => dJointTypePR,
    13 => dJointTypePU,
    14 => dJointTypePiston,
    15 => dJointTypeDBall,
    16 => dJointTypeDHinge,
    17 => dJointTypeTransmission,
    _ => throw ArgumentError('Unknown value for dJointType: $value'),
  };
}

/// Library initialization flags.
enum dInitODEFlags {
  /// < Thread local data is to be cleared explicitly on
  /// dCleanupODEAllDataForThread function call
  dInitFlagManualThreadCleanup(1);

  final int value;
  const dInitODEFlags(this.value);

  static dInitODEFlags fromValue(int value) => switch (value) {
    1 => dInitFlagManualThreadCleanup,
    _ => throw ArgumentError('Unknown value for dInitODEFlags: $value'),
  };
}

/// ODE data allocation flags.
enum dAllocateODEDataFlags {
  /// < Allocate basic data required for library to operate
  dAllocateFlagBasicData(0),

  /// < Allocate data for collision detection
  dAllocateFlagCollisionData(1),

  /// < Allocate all the possible data that is currently defined or will be
  /// defined in the future.
  dAllocateMaskAll(-1);

  final int value;
  const dAllocateODEDataFlags(this.value);

  static dAllocateODEDataFlags fromValue(int value) => switch (value) {
    0 => dAllocateFlagBasicData,
    1 => dAllocateFlagCollisionData,
    -1 => dAllocateMaskAll,
    _ => throw ArgumentError('Unknown value for dAllocateODEDataFlags: $value'),
  };
}

final class dSurfaceParameters extends ffi.Struct {
  /// must always be defined
  @ffi.Int()
  external int mode;

  @dReal()
  external double mu;

  /// only defined if the corresponding flag is set in mode
  @dReal()
  external double mu2;

  /// Rolling friction
  @dReal()
  external double rho;

  @dReal()
  external double rho2;

  /// Spinning friction
  @dReal()
  external double rhoN;

  /// Coefficient of restitution
  @dReal()
  external double bounce;

  /// Bouncing threshold
  @dReal()
  external double bounce_vel;

  @dReal()
  external double soft_erp;

  @dReal()
  external double soft_cfm;

  @dReal()
  external double motion1;

  @dReal()
  external double motion2;

  @dReal()
  external double motionN;

  @dReal()
  external double slip1;

  @dReal()
  external double slip2;
}

/// Describe the contact point between two geoms.
final class dContactGeom extends ffi.Struct {
  /// contact position
  @ffi.Array.multi([4])
  external ffi.Array<dReal> pos;

  /// normal vector
  @ffi.Array.multi([4])
  external ffi.Array<dReal> normal;

  /// penetration depth
  @dReal()
  external double depth;

  /// the colliding geoms
  external ffi.Pointer<dxGeom> g1;

  external ffi.Pointer<dxGeom> g2;

  /// (to be documented)
  @ffi.Int()
  external int side1;

  @ffi.Int()
  external int side2;
}

/// contact info used by contact joint
final class dContact extends ffi.Struct {
  external dSurfaceParameters surface;

  external dContactGeom geom;

  @ffi.Array.multi([4])
  external ffi.Array<dReal> fdir1;
}

final class dMass extends ffi.Struct {
  @dReal()
  external double mass;

  @ffi.Array.multi([4])
  external ffi.Array<dReal> c;

  @ffi.Array.multi([12])
  external ffi.Array<dReal> I;
}

/// User callback for geom-geom collision testing.
typedef dNearCallback =
    ffi.NativeFunction<
      ffi.Void Function(
        ffi.Pointer<ffi.Void> data,
        ffi.Pointer<dxGeom> o1,
        ffi.Pointer<dxGeom> o2,
      )
    >;

enum dMeshTriangleVertex {
  dMTV__MIN(0),
  dMTV_SECOND(1),
  dMTV_THIRD(2),
  dMTV__MAX(3);

  static const dMTV_FIRST = dMTV__MIN;

  final int value;
  const dMeshTriangleVertex(this.value);

  static dMeshTriangleVertex fromValue(int value) => switch (value) {
    0 => dMTV__MIN,
    1 => dMTV_SECOND,
    2 => dMTV_THIRD,
    3 => dMTV__MAX,
    _ => throw ArgumentError('Unknown value for dMeshTriangleVertex: $value'),
  };

  @override
  String toString() {
    if (this == dMTV__MIN)
      return "dMeshTriangleVertex.dMTV__MIN, dMeshTriangleVertex.dMTV_FIRST";
    return super.toString();
  }
}

const int FP_NAN = 0;

const int FP_INFINITE = 1;

const int FP_ZERO = 2;

const int FP_SUBNORMAL = 3;

const int FP_NORMAL = 4;

const int d_ERR_UNKNOWN = 0;

const int d_ERR_IASSERT = 1;

const int d_ERR_UASSERT = 2;

const int d_ERR_LCP = 3;

const int dParamLoStop = 0;

const int dParamHiStop = 1;

const int dParamVel = 2;

const int dParamLoVel = 3;

const int dParamHiVel = 4;

const int dParamFMax = 5;

const int dParamFudgeFactor = 6;

const int dParamBounce = 7;

const int dParamCFM = 8;

const int dParamStopERP = 9;

const int dParamStopCFM = 10;

const int dParamSuspensionERP = 11;

const int dParamSuspensionCFM = 12;

const int dParamERP = 13;

const int dParamsInGroup = 14;

const int dParamGroup1 = 0;

const int dParamLoStop1 = 0;

const int dParamHiStop1 = 1;

const int dParamVel1 = 2;

const int dParamLoVel1 = 3;

const int dParamHiVel1 = 4;

const int dParamFMax1 = 5;

const int dParamFudgeFactor1 = 6;

const int dParamBounce1 = 7;

const int dParamCFM1 = 8;

const int dParamStopERP1 = 9;

const int dParamStopCFM1 = 10;

const int dParamSuspensionERP1 = 11;

const int dParamSuspensionCFM1 = 12;

const int dParamERP1 = 13;

const int dParamGroup2 = 256;

const int dParamLoStop2 = 256;

const int dParamHiStop2 = 257;

const int dParamVel2 = 258;

const int dParamLoVel2 = 259;

const int dParamHiVel2 = 260;

const int dParamFMax2 = 261;

const int dParamFudgeFactor2 = 262;

const int dParamBounce2 = 263;

const int dParamCFM2 = 264;

const int dParamStopERP2 = 265;

const int dParamStopCFM2 = 266;

const int dParamSuspensionERP2 = 267;

const int dParamSuspensionCFM2 = 268;

const int dParamERP2 = 269;

const int dParamGroup3 = 512;

const int dParamLoStop3 = 512;

const int dParamHiStop3 = 513;

const int dParamVel3 = 514;

const int dParamLoVel3 = 515;

const int dParamHiVel3 = 516;

const int dParamFMax3 = 517;

const int dParamFudgeFactor3 = 518;

const int dParamBounce3 = 519;

const int dParamCFM3 = 520;

const int dParamStopERP3 = 521;

const int dParamStopCFM3 = 522;

const int dParamSuspensionERP3 = 523;

const int dParamSuspensionCFM3 = 524;

const int dParamERP3 = 525;

const int dParamGroup = 256;

const int dAMotorUser = 0;

const int dAMotorEuler = 1;

const int dTransmissionParallelAxes = 0;

const int dTransmissionIntersectingAxes = 1;

const int dTransmissionChainDrive = 2;

const int dContactMu2 = 1;

const int dContactAxisDep = 1;

const int dContactFDir1 = 2;

const int dContactBounce = 4;

const int dContactSoftERP = 8;

const int dContactSoftCFM = 16;

const int dContactMotion1 = 32;

const int dContactMotion2 = 64;

const int dContactMotionN = 128;

const int dContactSlip1 = 256;

const int dContactSlip2 = 512;

const int dContactRolling = 1024;

const int dContactApprox0 = 0;

const int dContactApprox1_1 = 4096;

const int dContactApprox1_2 = 8192;

const int dContactApprox1_N = 16384;

const int dContactApprox1 = 28672;

const int dWSTP_WorldIslandsIterationMaxThreads = 1;

const int dWSTP_IslandSteppingMaxThreads = 2;

const int dWSTP_LCPSolvingMaxThreads = 4;

const int dGeomCommonControlClass = 0;

const int dGeomColliderControlClass = 1;

const int dGeomCommonAnyControlCode = 0;

const int dGeomColliderSetMergeSphereContactsControlCode = 1;

const int dGeomColliderGetMergeSphereContactsControlCode = 2;

const int dGeomColliderMergeContactsValue__Default = 0;

const int dGeomColliderMergeContactsValue_None = 1;

const int dGeomColliderMergeContactsValue_Normals = 2;

const int dGeomColliderMergeContactsValue_Full = 3;

const int dMaxUserClasses = 4;

const int dSphereClass = 0;

const int dBoxClass = 1;

const int dCapsuleClass = 2;

const int dCylinderClass = 3;

const int dPlaneClass = 4;

const int dRayClass = 5;

const int dConvexClass = 6;

const int dGeomTransformClass = 7;

const int dTriMeshClass = 8;

const int dHeightfieldClass = 9;

const int dFirstSpaceClass = 10;

const int dSimpleSpaceClass = 10;

const int dHashSpaceClass = 11;

const int dSweepAndPruneSpaceClass = 12;

const int dQuadTreeSpaceClass = 13;

const int dLastSpaceClass = 13;

const int dFirstUserClass = 14;

const int dLastUserClass = 17;

const int dGeomNumClasses = 18;

const int dTRIMESHDATA__MIN = 0;

const int dTRIMESHDATA_FACE_NORMALS = 0;

const int dTRIMESHDATA_USE_FLAGS = 1;

const int dTRIMESHDATA__MAX = 2;

const int TRIMESH_FACE_NORMALS = 0;

const int dMESHDATAUSE_EDGE1 = 1;

const int dMESHDATAUSE_EDGE2 = 2;

const int dMESHDATAUSE_EDGE3 = 4;

const int dMESHDATAUSE_VERTEX1 = 8;

const int dMESHDATAUSE_VERTEX2 = 16;

const int dMESHDATAUSE_VERTEX3 = 32;

const int dTRIDATAPREPROCESS_BUILD__MIN = 0;

const int dTRIDATAPREPROCESS_BUILD_CONCAVE_EDGES = 0;

const int dTRIDATAPREPROCESS_BUILD_FACE_ANGLES = 1;

const int dTRIDATAPREPROCESS_BUILD__MAX = 2;

const int dTRIDATAPREPROCESS_FACE_ANGLES_EXTRA__MIN = 0;

const int dTRIDATAPREPROCESS_FACE_ANGLES_EXTRA_BYTE_POSITIVE = 0;

const int dTRIDATAPREPROCESS_FACE_ANGLES_EXTRA_BYTE_ALL = 1;

const int dTRIDATAPREPROCESS_FACE_ANGLES_EXTRA_WORD_ALL = 2;

const int dTRIDATAPREPROCESS_FACE_ANGLES_EXTRA__MAX = 3;

const int dTRIDATAPREPROCESS_FACE_ANGLES_EXTRA__DEFAULT = 0;
